const functions = require('firebase-functions');

exports.extract_video_summary = functions.https.onRequest((req, res) => {
  res.set('Access-Control-Allow-Origin', '*');
  if (req.method === 'OPTIONS') {
    res.set('Access-Control-Allow-Methods', 'POST, GET, OPTIONS');
    res.set('Access-Control-Allow-Headers', 'Content-Type');
    return res.status(204).send('');
  }

  const { videoUrl, videoId, platform } = req.body || {};
  const now = Date.now();

  const sample = {
    keyPoints: [
      { text: 'Intro and problem statement', start: 0.0, end: 12.5 },
      { text: 'Demo of solution', start: 13.0, end: 75.0 },
      { text: 'Final summary and takeaways', start: 300.0, end: 315.0 }
    ],
    transcript: 'This is a stub transcript generated by the emulator. Replace with a real extractor when billing is enabled.',
    metadata: {
      videoUrl: videoUrl || null,
      videoId: videoId || null,
      platform: platform || 'unknown',
      extractedAt: new Date(now).toISOString(),
      source: 'stub-emulator'
    }
  };

  res.json(sample);
});
